ios_deployment_target = '14.0'
$firebaseVersion = '11.0.0'

platform :ios, ios_deployment_target
use_frameworks!

target 'cybergarden2024' do
  pod 'TinyConstraints', '4.0.2'
  pod 'PKHUD', '5.3.0'
  pod 'Firebase/Analytics', $firebaseVersion
  pod 'Firebase/Crashlytics', $firebaseVersion
  pod 'UIViewController+KeyboardAnimation', '1.3'
  pod 'Toast-Swift', '5.1.1'
  pod 'Moya/Combine', '15.0.0'
  pod 'AMPopTip', '4.12.0'
  pod 'FloatingPanel', '2.8.5'
  pod 'SDWebImage', '5.19.6'
  pod 'RxSwift', '6.7.1'
  pod 'SVProgressHUD', '2.3.1'
  pod 'RxCocoa', '6.7.1'
  pod 'ScrollableGraphView'
  pod 'SwiftCharts', '0.6.5'
  pod 'PieCharts'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < ios_deployment_target.to_f
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ios_deployment_target
        end
      end
    end
  end
end
